version: '3.8'

services:
  # PostgreSQL 17 service
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: b3_trade_aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application service
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/b3_trade_aggregator?sslmode=disable
      API_PORT: 8080
    volumes:
      - ./data:/app/data  # Mount para arquivos de dados
    restart: unless-stopped

volumes:
  postgres_data:
